version: '3'

services:
  snipeit:
    build:

      context: .
      dockerfile: Dockerfile.alpine
      args:
        - APP_ENV=${APP_ENV}
    container_name: snipeit
    ports:
    - "8000:80"
    volumes:
    # the /tmp/snipe-it is a synced folder using rsync.
    # this is needed due to the permission changes applied by docker when mounting afolder
    - /tmp/snipe-it:/var/www/html
    depends_on:
    - mariadb
    - redis
    env_file:
    - .env.docker
    networks:
    - snipeit-backend

  mariadb:
    image: mariadb:10.6.4-focal
    volumes:
    - db:/var/lib/mysql
    env_file:
    - .env.docker
    networks:
    - snipeit-backend
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2.5-buster
    networks:
    - snipeit-backend

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
    # - 1025:1025
    - "8025:8025"
    networks:
    - snipeit-backend


volumes:
  db: {}

networks:
  snipeit-backend: {}
